/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package okno;

import java.util.List;
import kniznica.*;
import kniznica.Film;
import kniznica.SQLFilm;
import kniznica.SQLZaner;
import kniznica.Zaner;

/**
 *
 * @author Rastislav
 */
public class menuOkno extends javax.swing.JFrame {
private SQLZaner ZanerDao = new SQLZaner();
private SQLFilm FilmDao = new SQLFilm();
   
    /**
     * Creates new form menuOkno
     */
    public menuOkno(java.awt.Frame parent, boolean modal) {
        refreshZanre();
        initComponents();
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        Zanre = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        Filmy = new javax.swing.JList();
        PridajFilm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Zanre.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Zanre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZanreMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Zanre);

        Filmy.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Filmy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilmyMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Filmy);

        PridajFilm.setText("Pridaj");
        PridajFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajFilmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(PridajFilm)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PridajFilm)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
      private void refreshZanre() {
       List<Zaner> zanre = ZanerDao.dajVsetkych();
       Zanre.setListData(zanre.toArray());
       
    }  
    
    private void ZanreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZanreMouseClicked
        if(evt.getClickCount() == 2){
        Zaner zaner = (Zaner) Zanre.getSelectedValue();
        refreshFilmy(zaner.getMeno());
        }
    }//GEN-LAST:event_ZanreMouseClicked

    private void PridajFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajFilmActionPerformed
        Film film = new Film();
        PridatFilmForm pridatFilm = new PridatFilmForm(this, true, film);
        pridatFilm.setVisible(true);
    }//GEN-LAST:event_PridajFilmActionPerformed

    private void FilmyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilmyMouseClicked
        if(evt.getClickCount() == 2){
        Film film = (Film) Filmy.getSelectedValue();
        FilmInfoForm filmInfoForm = new FilmInfoForm(this, false,film);
        filmInfoForm.setVisible(true);
        }
    }//GEN-LAST:event_FilmyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menuOkno dialog = new menuOkno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList Filmy;
    private javax.swing.JButton PridajFilm;
    private javax.swing.JList Zanre;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    private void refreshFilmy(String meno) {
        List<Film> filmy = FilmDao.dajZanre(meno);
        Filmy.setListData(filmy.toArray());
    }

    
    
    
    
    
    
}
