/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package okno;

import java.awt.Frame;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kniznica.Film;
import kniznica.Film;
import kniznica.FilmDao;
import kniznica.FilmDao;
import kniznica.FilmDaoFactory;
import kniznica.FilmDaoFactory;
import kniznica.SQLFilm;

/**
 *
 * @author Matúš
 */
public class PridatFilmForm extends javax.swing.JDialog {
    private Film film;
    
    //private FilmDao filmDao = FilmDaoFactory.instance.GetFilmDao();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-mm-dd");
    /**
     * Creates new form PridatFilmForm
     */
    public PridatFilmForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    PridatFilmForm(Frame parent, boolean modal, Film film){
     super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
    
            this.film=film; 
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDTextField = new javax.swing.JTextField();
        HodnotenieTextField = new javax.swing.JTextField();
        NazovTextField = new javax.swing.JTextField();
        IDLabel = new javax.swing.JLabel();
        HodnotenieLabel = new javax.swing.JLabel();
        NazovLabel = new javax.swing.JLabel();
        HerciLabel = new javax.swing.JLabel();
        HerciTextField = new javax.swing.JTextField();
        ZanerLabel = new javax.swing.JLabel();
        ZanerTextField = new javax.swing.JTextField();
        DlzkaLabel = new javax.swing.JLabel();
        DlzkaTextField = new javax.swing.JTextField();
        PremieraLabel = new javax.swing.JLabel();
        PremieraTextField = new javax.swing.JTextField();
        StatLabel = new javax.swing.JLabel();
        StatTextField = new javax.swing.JTextField();
        ObsahLabel = new javax.swing.JLabel();
        TrailerLabel = new javax.swing.JLabel();
        TrailerTextField = new javax.swing.JTextField();
        RecenziaLabel = new javax.swing.JLabel();
        RecenziaTextField = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObsahTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });

        IDLabel.setText("ID");

        HodnotenieLabel.setText("Hodnotenie");

        NazovLabel.setText("Nazov");

        HerciLabel.setText("Herci");

        ZanerLabel.setText("Zaner");

        DlzkaLabel.setText("Dlzka");

        PremieraLabel.setText("Premiera");

        StatLabel.setText("Stat");

        ObsahLabel.setText("Obsah");

        TrailerLabel.setText("Trailer");

        RecenziaLabel.setText("Recenzia");

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ObsahTextArea.setColumns(20);
        ObsahTextArea.setRows(5);
        jScrollPane1.setViewportView(ObsahTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PremieraLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ZanerLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PremieraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZanerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DlzkaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DlzkaTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StatLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(OKButton)
                                .addGap(27, 27, 27)
                                .addComponent(CancelButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(HerciLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(HerciTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NazovLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                                .addComponent(HodnotenieLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(HodnotenieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(NazovTextField))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TrailerLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TrailerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RecenziaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RecenziaTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ObsahLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HodnotenieLabel)
                    .addComponent(HodnotenieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NazovLabel)
                    .addComponent(NazovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HerciLabel)
                    .addComponent(HerciTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZanerLabel)
                    .addComponent(ZanerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DlzkaLabel)
                    .addComponent(DlzkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PremieraLabel)
                    .addComponent(PremieraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatLabel)
                    .addComponent(StatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(ObsahLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TrailerLabel)
                    .addComponent(TrailerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecenziaLabel)
                    .addComponent(RecenziaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKButton)
                    .addComponent(CancelButton))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
       int id;
        String kont1=IDTextField.getText();
         if(kont1.trim().isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Nevyplnili ste id!");
            return;
        }         else{ id=Integer.parseInt(IDTextField.getText());}
        film.setId(id);
       
        int hodnotenie;
        String kont2=HodnotenieTextField.getText();
        if(kont2.trim().isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Nevyplnili ste hodnotenie!");
            return;
        }   else{hodnotenie=Integer.parseInt(HodnotenieTextField.getText());}      
        film.setHodtenie(hodnotenie);
        
        String nazov= NazovTextField.getText();
        if(nazov.trim().isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Nevyplnili ste nazov!");
            return;
        }         
        film.setNazov(nazov);
        String herci = HerciTextField.getText();
        if(herci.trim().isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Nevyplnili ste hercov!");
            return;
        }         
        film.setHerci(herci);
        String zaner = ZanerTextField.getText();
      if(zaner.trim().isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Nevyplnili ste zaner!");
            return;
        }         
        int dlzka;
        String kont3=DlzkaTextField.getText();
        if(kont3.trim().isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Nevyplnili ste dlzku filmu!");
            return;
        }    else{dlzka = Integer.parseInt(DlzkaTextField.getText());}     
       
        String stat = StatTextField.getText();
                if(stat.trim().isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Nevyplnili ste stat!");
            return;
        }         
       film.setStat(stat);
       
        Date datum = null;
        try {
            datum = sdf.parse(PremieraTextField.getText());
        } catch (ParseException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(datum==null) {
                 JOptionPane.showMessageDialog(this, "Nevyplnili ste premieru!");
            return;
        }         
        film.setPremiera(datum);
        
        String obsah = ObsahTextArea.getText();
        if(obsah.trim().isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Nevyplnili ste obsah!");
            return;
        }      
        
        film.setObsah(obsah);
        URL trailer=null;
        try {
            trailer = new URL(TrailerTextField.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         if(trailer==null) {
                 JOptionPane.showMessageDialog(this, "Nevyplnili ste trailer!");
            return;
        } 
        film.setTrailer(trailer);   
      
        URL recenzia = null;
        try {
            recenzia = new URL(RecenziaTextField.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         if(recenzia==null) {
                 JOptionPane.showMessageDialog(this, "Nevyplnili ste recenziu!");
            return;
        } 
         film.setRecenzie(recenzia);
         
        SQLFilm sqlfilm = new SQLFilm();
        sqlfilm.pridat(film);
    }//GEN-LAST:event_OKButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PridatFilmForm dialog = new PridatFilmForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel DlzkaLabel;
    private javax.swing.JTextField DlzkaTextField;
    private javax.swing.JLabel HerciLabel;
    private javax.swing.JTextField HerciTextField;
    private javax.swing.JLabel HodnotenieLabel;
    private javax.swing.JTextField HodnotenieTextField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JLabel NazovLabel;
    private javax.swing.JTextField NazovTextField;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel ObsahLabel;
    private javax.swing.JTextArea ObsahTextArea;
    private javax.swing.JLabel PremieraLabel;
    private javax.swing.JTextField PremieraTextField;
    private javax.swing.JLabel RecenziaLabel;
    private javax.swing.JTextField RecenziaTextField;
    private javax.swing.JLabel StatLabel;
    private javax.swing.JTextField StatTextField;
    private javax.swing.JLabel TrailerLabel;
    private javax.swing.JTextField TrailerTextField;
    private javax.swing.JLabel ZanerLabel;
    private javax.swing.JTextField ZanerTextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
