/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package okno;

import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import kniznica.*;

/**
 *
 * @author Matúš
 */
public class PridatFilmFormCisto extends javax.swing.JFrame {

    private FilmDao sqlfilm = FilmDaoFactory.INSTANCE.getFilmDao();
    private Film film;
    private int dlzka;
    private Date premiera;
    private String obsah;
    private URL recenzia;
    private URL trailer;
    private Set<Herec> herci = new HashSet<>();
    private Set<Stat> staty = new HashSet<>();
    private Set<Zaner> zanre = new HashSet<>();
    private Set<Reziser> reziseri = new HashSet<>();
    private Set<Scenarista> scenaristi = new HashSet<>();

    /**
     * Creates new form PridatFilmFormCisto
     */
    public PridatFilmFormCisto(java.awt.Frame parent, boolean modal) {
        initComponents();

    }

    PridatFilmFormCisto(Frame parent, boolean modal, Film film) {
        //  super(parent, modal);
        initComponents();
        refreshHerci();
        refreshZanre();
        setLocationRelativeTo(null);

        this.film = film;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PridajHercaForm = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MenoHercaForm = new javax.swing.JTextField();
        ZivotopisHercaForm = new javax.swing.JTextField();
        PridajHercaButton = new javax.swing.JToggleButton();
        ZrusHercaButton = new javax.swing.JToggleButton();
        PridajStatForm = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        StatyTextField = new javax.swing.JTextField();
        PridajStatButton = new javax.swing.JToggleButton();
        ZrusHercaButton1 = new javax.swing.JToggleButton();
        PridajZanerForm = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        ZanerTextField = new javax.swing.JTextField();
        PridajZanerButton = new javax.swing.JToggleButton();
        ZrusZanerFormButton = new javax.swing.JToggleButton();
        PridajScenaristuForm = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MenoScenaristuTextfield = new javax.swing.JTextField();
        ZivotopisScenaristuTextField = new javax.swing.JTextField();
        PridajScenaristuButton = new javax.swing.JToggleButton();
        ZrusScenaristuButton = new javax.swing.JToggleButton();
        PridajReziseraForm = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        MenoReziseraTextField = new javax.swing.JTextField();
        ZivotopisReziseraTextField = new javax.swing.JTextField();
        PridajReziseraButton = new javax.swing.JToggleButton();
        ZrusReziseraButton = new javax.swing.JToggleButton();
        PridajPremieruForm = new javax.swing.JFrame();
        pridajPremieruButton = new javax.swing.JToggleButton();
        ZrusPremieruButton = new javax.swing.JToggleButton();
        denTextField = new javax.swing.JTextField();
        rokTextField = new javax.swing.JTextField();
        mesiacTextField = new javax.swing.JTextField();
        DenLabel = new javax.swing.JLabel();
        MesiacLabel = new javax.swing.JLabel();
        rokLabel = new javax.swing.JLabel();
        PridajObsahForm = new javax.swing.JFrame();
        PridajObsahButton = new javax.swing.JToggleButton();
        ZrusObsahButton = new javax.swing.JToggleButton();
        ObsahLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObsahTextArea = new javax.swing.JTextArea();
        PridajRecenziuForm = new javax.swing.JFrame();
        RecenziaLabel = new javax.swing.JLabel();
        RecenziaTextField = new javax.swing.JTextField();
        PridajRecenziuButton = new javax.swing.JToggleButton();
        ZrusRecenziuButton = new javax.swing.JToggleButton();
        PridajTrailerForm = new javax.swing.JFrame();
        RecenziaLabel2 = new javax.swing.JLabel();
        TrailerTextField = new javax.swing.JTextField();
        PridajTrailerButton = new javax.swing.JToggleButton();
        ZrusTrailerButton = new javax.swing.JToggleButton();
        PridajDlzkuForm = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        DlzkaTextField = new javax.swing.JTextField();
        PridajDlzkuButton = new javax.swing.JToggleButton();
        ZrusDlzkuButton = new javax.swing.JToggleButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        HerciList1 = new javax.swing.JList();
        ZanreLabel1 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        ZanreList1 = new javax.swing.JList();
        HerciLabel2 = new javax.swing.JLabel();
        StatLabel1 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        StatyList1 = new javax.swing.JList();
        PridajHercaButton1 = new javax.swing.JButton();
        ZmazHercaButton1 = new javax.swing.JButton();
        PridajZanerButton1 = new javax.swing.JButton();
        ZmazZanerButton1 = new javax.swing.JButton();
        PridajStatButton1 = new javax.swing.JButton();
        ZmazStatButton1 = new javax.swing.JButton();
        PridajReziseraButton1 = new javax.swing.JButton();
        ZmazReziseraButton1 = new javax.swing.JButton();
        PridajScenaristuButton1 = new javax.swing.JButton();
        ZmazScenaristuButton1 = new javax.swing.JButton();
        HodnotenieTextField1 = new javax.swing.JTextField();
        NazovTextField1 = new javax.swing.JTextField();
        HodnotenieLabel2 = new javax.swing.JLabel();
        NazovLabel1 = new javax.swing.JLabel();
        PridajFilmButton1 = new javax.swing.JButton();
        StornoButton1 = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        ReziserList1 = new javax.swing.JList();
        ReziserLabel1 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        ScenaristaList1 = new javax.swing.JList();
        ScenaristaLabel2 = new javax.swing.JLabel();
        PridajObsah = new javax.swing.JButton();
        PridajPRemieruButton = new javax.swing.JButton();
        PridajDlzku1 = new javax.swing.JButton();
        PridajRecenziu = new javax.swing.JButton();
        PridajTrailerButton1 = new javax.swing.JButton();

        PridajHercaForm.setSize(new java.awt.Dimension(250, 250));

        jLabel1.setText("Meno:");

        jLabel2.setText("Zivotopis:");

        PridajHercaButton.setText("Pridaj");
        PridajHercaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajHercaButtonActionPerformed(evt);
            }
        });

        ZrusHercaButton.setText("Cancel");
        ZrusHercaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZrusHercaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PridajHercaFormLayout = new javax.swing.GroupLayout(PridajHercaForm.getContentPane());
        PridajHercaForm.getContentPane().setLayout(PridajHercaFormLayout);
        PridajHercaFormLayout.setHorizontalGroup(
            PridajHercaFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajHercaFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PridajHercaFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(PridajHercaFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MenoHercaForm)
                    .addComponent(ZivotopisHercaForm, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PridajHercaFormLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(PridajHercaButton)
                .addGap(18, 18, 18)
                .addComponent(ZrusHercaButton)
                .addContainerGap())
        );
        PridajHercaFormLayout.setVerticalGroup(
            PridajHercaFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajHercaFormLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PridajHercaFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MenoHercaForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PridajHercaFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ZivotopisHercaForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(PridajHercaFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PridajHercaButton)
                    .addComponent(ZrusHercaButton))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        PridajStatForm.setSize(new java.awt.Dimension(250, 250));

        jLabel3.setText("Nazov");

        PridajStatButton.setText("Pridaj");
        PridajStatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajStatButtonActionPerformed(evt);
            }
        });

        ZrusHercaButton1.setText("Cancel");
        ZrusHercaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZrusHercaButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PridajStatFormLayout = new javax.swing.GroupLayout(PridajStatForm.getContentPane());
        PridajStatForm.getContentPane().setLayout(PridajStatFormLayout);
        PridajStatFormLayout.setHorizontalGroup(
            PridajStatFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajStatFormLayout.createSequentialGroup()
                .addGroup(PridajStatFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PridajStatFormLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(StatyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PridajStatFormLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(PridajStatButton)
                        .addGap(18, 18, 18)
                        .addComponent(ZrusHercaButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PridajStatFormLayout.setVerticalGroup(
            PridajStatFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajStatFormLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PridajStatFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(StatyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(PridajStatFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PridajStatButton)
                    .addComponent(ZrusHercaButton1))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        PridajZanerForm.setSize(new java.awt.Dimension(250, 250));

        jLabel5.setText("Meno:");

        PridajZanerButton.setText("Pridaj");
        PridajZanerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajZanerButtonActionPerformed(evt);
            }
        });

        ZrusZanerFormButton.setText("Cancel");
        ZrusZanerFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZrusZanerFormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PridajZanerFormLayout = new javax.swing.GroupLayout(PridajZanerForm.getContentPane());
        PridajZanerForm.getContentPane().setLayout(PridajZanerFormLayout);
        PridajZanerFormLayout.setHorizontalGroup(
            PridajZanerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajZanerFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PridajZanerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PridajZanerFormLayout.createSequentialGroup()
                        .addComponent(PridajZanerButton)
                        .addGap(30, 30, 30)
                        .addComponent(ZrusZanerFormButton))
                    .addGroup(PridajZanerFormLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(ZanerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PridajZanerFormLayout.setVerticalGroup(
            PridajZanerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajZanerFormLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PridajZanerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ZanerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(PridajZanerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PridajZanerButton)
                    .addComponent(ZrusZanerFormButton))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        PridajScenaristuForm.setSize(new java.awt.Dimension(250, 250));

        jLabel7.setText("Meno:");

        jLabel8.setText("Zivotopis:");

        PridajScenaristuButton.setText("Pridaj");
        PridajScenaristuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajScenaristuButtonActionPerformed(evt);
            }
        });

        ZrusScenaristuButton.setText("Cancel");
        ZrusScenaristuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZrusScenaristuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PridajScenaristuFormLayout = new javax.swing.GroupLayout(PridajScenaristuForm.getContentPane());
        PridajScenaristuForm.getContentPane().setLayout(PridajScenaristuFormLayout);
        PridajScenaristuFormLayout.setHorizontalGroup(
            PridajScenaristuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PridajScenaristuFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PridajScenaristuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PridajScenaristuFormLayout.createSequentialGroup()
                        .addGroup(PridajScenaristuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(PridajScenaristuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenoScenaristuTextfield)
                            .addComponent(ZivotopisScenaristuTextField)))
                    .addGroup(PridajScenaristuFormLayout.createSequentialGroup()
                        .addGap(0, 116, Short.MAX_VALUE)
                        .addComponent(PridajScenaristuButton)
                        .addGap(18, 18, 18)
                        .addComponent(ZrusScenaristuButton)))
                .addGap(93, 93, 93))
        );
        PridajScenaristuFormLayout.setVerticalGroup(
            PridajScenaristuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajScenaristuFormLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PridajScenaristuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(MenoScenaristuTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PridajScenaristuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(ZivotopisScenaristuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(PridajScenaristuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PridajScenaristuButton)
                    .addComponent(ZrusScenaristuButton))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        PridajReziseraForm.setSize(new java.awt.Dimension(250, 250));

        jLabel9.setText("Meno:");

        jLabel10.setText("Zivotopis:");

        PridajReziseraButton.setText("Pridaj");
        PridajReziseraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajReziseraButtonActionPerformed(evt);
            }
        });

        ZrusReziseraButton.setText("Cancel");
        ZrusReziseraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZrusReziseraButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PridajReziseraFormLayout = new javax.swing.GroupLayout(PridajReziseraForm.getContentPane());
        PridajReziseraForm.getContentPane().setLayout(PridajReziseraFormLayout);
        PridajReziseraFormLayout.setHorizontalGroup(
            PridajReziseraFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajReziseraFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PridajReziseraFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(PridajReziseraFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MenoReziseraTextField)
                    .addComponent(ZivotopisReziseraTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PridajReziseraFormLayout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(PridajReziseraButton)
                .addGap(18, 18, 18)
                .addComponent(ZrusReziseraButton)
                .addContainerGap())
        );
        PridajReziseraFormLayout.setVerticalGroup(
            PridajReziseraFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajReziseraFormLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PridajReziseraFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(MenoReziseraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PridajReziseraFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(ZivotopisReziseraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(PridajReziseraFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PridajReziseraButton)
                    .addComponent(ZrusReziseraButton))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        PridajPremieruForm.setSize(new java.awt.Dimension(250, 250));

        pridajPremieruButton.setText("Pridaj");
        pridajPremieruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajPremieruButtonActionPerformed(evt);
            }
        });

        ZrusPremieruButton.setText("Cancel");
        ZrusPremieruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZrusPremieruButtonActionPerformed(evt);
            }
        });

        denTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                denTextFieldKeyTyped(evt);
            }
        });

        rokTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rokTextFieldKeyTyped(evt);
            }
        });

        mesiacTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesiacTextFieldKeyTyped(evt);
            }
        });

        DenLabel.setText("den");

        MesiacLabel.setText("mesiac");

        rokLabel.setText("rok");

        javax.swing.GroupLayout PridajPremieruFormLayout = new javax.swing.GroupLayout(PridajPremieruForm.getContentPane());
        PridajPremieruForm.getContentPane().setLayout(PridajPremieruFormLayout);
        PridajPremieruFormLayout.setHorizontalGroup(
            PridajPremieruFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajPremieruFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PridajPremieruFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PridajPremieruFormLayout.createSequentialGroup()
                        .addComponent(rokLabel)
                        .addGap(39, 39, 39)
                        .addComponent(MesiacLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DenLabel))
                    .addGroup(PridajPremieruFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PridajPremieruFormLayout.createSequentialGroup()
                            .addComponent(pridajPremieruButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZrusPremieruButton))
                        .addGroup(PridajPremieruFormLayout.createSequentialGroup()
                            .addComponent(rokTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mesiacTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(denTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        PridajPremieruFormLayout.setVerticalGroup(
            PridajPremieruFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajPremieruFormLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PridajPremieruFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DenLabel)
                    .addComponent(MesiacLabel)
                    .addComponent(rokLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PridajPremieruFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rokTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesiacTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(denTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PridajPremieruFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridajPremieruButton)
                    .addComponent(ZrusPremieruButton))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        PridajObsahForm.setSize(new java.awt.Dimension(250, 250));

        PridajObsahButton.setText("Pridaj");
        PridajObsahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajObsahButtonActionPerformed(evt);
            }
        });

        ZrusObsahButton.setText("Cancel");
        ZrusObsahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZrusObsahButtonActionPerformed(evt);
            }
        });

        ObsahLabel.setText("Obsah");

        ObsahTextArea.setColumns(20);
        ObsahTextArea.setRows(5);
        jScrollPane1.setViewportView(ObsahTextArea);

        javax.swing.GroupLayout PridajObsahFormLayout = new javax.swing.GroupLayout(PridajObsahForm.getContentPane());
        PridajObsahForm.getContentPane().setLayout(PridajObsahFormLayout);
        PridajObsahFormLayout.setHorizontalGroup(
            PridajObsahFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PridajObsahFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ObsahLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PridajObsahFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ZrusObsahButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PridajObsahButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        PridajObsahFormLayout.setVerticalGroup(
            PridajObsahFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajObsahFormLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PridajObsahFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addGroup(PridajObsahFormLayout.createSequentialGroup()
                        .addGroup(PridajObsahFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ObsahLabel)
                            .addComponent(PridajObsahButton))
                        .addGap(18, 18, 18)
                        .addComponent(ZrusObsahButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        PridajRecenziuForm.setSize(new java.awt.Dimension(250, 250));

        RecenziaLabel.setText("Recenzia");

        PridajRecenziuButton.setText("Pridaj");
        PridajRecenziuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajRecenziuButtonActionPerformed(evt);
            }
        });

        ZrusRecenziuButton.setText("Cancel");
        ZrusRecenziuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZrusRecenziuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PridajRecenziuFormLayout = new javax.swing.GroupLayout(PridajRecenziuForm.getContentPane());
        PridajRecenziuForm.getContentPane().setLayout(PridajRecenziuFormLayout);
        PridajRecenziuFormLayout.setHorizontalGroup(
            PridajRecenziuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajRecenziuFormLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(RecenziaLabel)
                .addGap(18, 18, 18)
                .addGroup(PridajRecenziuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PridajRecenziuFormLayout.createSequentialGroup()
                        .addComponent(PridajRecenziuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ZrusRecenziuButton))
                    .addComponent(RecenziaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PridajRecenziuFormLayout.setVerticalGroup(
            PridajRecenziuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajRecenziuFormLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PridajRecenziuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecenziaLabel)
                    .addComponent(RecenziaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(PridajRecenziuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PridajRecenziuButton)
                    .addComponent(ZrusRecenziuButton))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        PridajTrailerForm.setSize(new java.awt.Dimension(250, 250));

        RecenziaLabel2.setText("Trailer");

        PridajTrailerButton.setText("Pridaj");
        PridajTrailerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajTrailerButtonActionPerformed(evt);
            }
        });

        ZrusTrailerButton.setText("Cancel");
        ZrusTrailerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZrusTrailerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PridajTrailerFormLayout = new javax.swing.GroupLayout(PridajTrailerForm.getContentPane());
        PridajTrailerForm.getContentPane().setLayout(PridajTrailerFormLayout);
        PridajTrailerFormLayout.setHorizontalGroup(
            PridajTrailerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajTrailerFormLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(RecenziaLabel2)
                .addGap(18, 18, 18)
                .addGroup(PridajTrailerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PridajTrailerFormLayout.createSequentialGroup()
                        .addComponent(PridajTrailerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ZrusTrailerButton))
                    .addComponent(TrailerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PridajTrailerFormLayout.setVerticalGroup(
            PridajTrailerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PridajTrailerFormLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PridajTrailerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecenziaLabel2)
                    .addComponent(TrailerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(PridajTrailerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PridajTrailerButton)
                    .addComponent(ZrusTrailerButton))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        PridajDlzkuForm.setSize(new java.awt.Dimension(250, 250));
        PridajDlzkuForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PridajDlzkuFormKeyTyped(evt);
            }
        });

        jLabel19.setText("Dlzka");

        PridajDlzkuButton.setText("Pridaj");
        PridajDlzkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajDlzkuButtonActionPerformed(evt);
            }
        });

        ZrusDlzkuButton.setText("Cancel");
        ZrusDlzkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZrusDlzkuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PridajDlzkuFormLayout = new javax.swing.GroupLayout(PridajDlzkuForm.getContentPane());
        PridajDlzkuForm.getContentPane().setLayout(PridajDlzkuFormLayout);
        PridajDlzkuFormLayout.setHorizontalGroup(
            PridajDlzkuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajDlzkuFormLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PridajDlzkuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PridajDlzkuFormLayout.createSequentialGroup()
                        .addComponent(PridajDlzkuButton)
                        .addGap(31, 31, 31)
                        .addComponent(ZrusDlzkuButton))
                    .addGroup(PridajDlzkuFormLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(DlzkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PridajDlzkuFormLayout.setVerticalGroup(
            PridajDlzkuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PridajDlzkuFormLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PridajDlzkuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(DlzkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PridajDlzkuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PridajDlzkuButton)
                    .addComponent(ZrusDlzkuButton))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane8.setViewportView(HerciList1);

        ZanreLabel1.setText("Zanre");

        jScrollPane9.setViewportView(ZanreList1);

        HerciLabel2.setText("Herci");

        StatLabel1.setText("Staty");

        jScrollPane10.setViewportView(StatyList1);

        PridajHercaButton1.setText("PridajHerca");
        PridajHercaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajHercaButton1ActionPerformed(evt);
            }
        });

        ZmazHercaButton1.setText("ZmazHerca");
        ZmazHercaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZmazHercaButton1ActionPerformed(evt);
            }
        });

        PridajZanerButton1.setText("PridajZaner");
        PridajZanerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajZanerButton1ActionPerformed(evt);
            }
        });

        ZmazZanerButton1.setText("ZmazZaner");
        ZmazZanerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZmazZanerButton1ActionPerformed(evt);
            }
        });

        PridajStatButton1.setText("PridajStat");
        PridajStatButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajStatButton1ActionPerformed(evt);
            }
        });

        ZmazStatButton1.setText("ZmazStat");
        ZmazStatButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZmazStatButton1ActionPerformed(evt);
            }
        });

        PridajReziseraButton1.setText("PridajRezisera");
        PridajReziseraButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajReziseraButton1ActionPerformed(evt);
            }
        });

        ZmazReziseraButton1.setText("ZmazRezisera");
        ZmazReziseraButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZmazReziseraButton1ActionPerformed(evt);
            }
        });

        PridajScenaristuButton1.setText("PridajScenaristu");
        PridajScenaristuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajScenaristuButton1ActionPerformed(evt);
            }
        });

        ZmazScenaristuButton1.setText("ZmazScenaristu");
        ZmazScenaristuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZmazScenaristuButton1ActionPerformed(evt);
            }
        });

        HodnotenieTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HodnotenieTextField1KeyTyped(evt);
            }
        });

        HodnotenieLabel2.setText("Hodnotenie");

        NazovLabel1.setText("Nazov");

        PridajFilmButton1.setText("PridajFilm");
        PridajFilmButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajFilmButton1ActionPerformed(evt);
            }
        });

        StornoButton1.setText("Storno");
        StornoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StornoButton1ActionPerformed(evt);
            }
        });

        jScrollPane14.setViewportView(ReziserList1);

        ReziserLabel1.setText("Reziser");

        jScrollPane15.setViewportView(ScenaristaList1);

        ScenaristaLabel2.setText("Scenarista");

        PridajObsah.setText("Pridaj obsah");
        PridajObsah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajObsahActionPerformed(evt);
            }
        });

        PridajPRemieruButton.setText("Pridaj premieru");
        PridajPRemieruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajPRemieruButtonActionPerformed(evt);
            }
        });

        PridajDlzku1.setText("Pridaj dlzku");
        PridajDlzku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajDlzku1ActionPerformed(evt);
            }
        });

        PridajRecenziu.setText("Pridaj recenziu");
        PridajRecenziu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajRecenziuActionPerformed(evt);
            }
        });

        PridajTrailerButton1.setText("Pridaj trailer");
        PridajTrailerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajTrailerButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NazovLabel1)
                        .addGap(16, 16, 16)
                        .addComponent(NazovTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(HodnotenieLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HerciLabel2)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StatLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReziserLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(PridajFilmButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(StornoButton1))
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PridajHercaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZmazHercaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PridajStatButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZmazStatButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PridajReziseraButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZmazReziseraButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(HodnotenieTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ZanreLabel1)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ScenaristaLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ZmazZanerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PridajZanerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PridajScenaristuButton1)
                                    .addComponent(ZmazScenaristuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PridajPRemieruButton, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(PridajTrailerButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PridajDlzku1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PridajRecenziu, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(PridajObsah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(61, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NazovTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HodnotenieTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NazovLabel1)
                            .addComponent(HodnotenieLabel2))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ZanreLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(ZmazHercaButton1))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PridajZanerButton1)
                                .addGap(55, 55, 55)
                                .addComponent(ZmazZanerButton1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(HerciLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PridajHercaButton1)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatLabel1)
                    .addComponent(ScenaristaLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(PridajStatButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZmazStatButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(PridajScenaristuButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZmazScenaristuButton1))
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ReziserLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PridajReziseraButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ZmazReziseraButton1))
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PridajFilmButton1)
                            .addComponent(StornoButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PridajPRemieruButton)
                            .addComponent(PridajRecenziu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PridajTrailerButton1)
                            .addComponent(PridajObsah))
                        .addGap(18, 18, 18)
                        .addComponent(PridajDlzku1)
                        .addGap(235, 235, 235))))
        );

        jScrollPane7.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StornoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StornoButton1ActionPerformed
        this.setVisible(false);
        this.disable();
    }//GEN-LAST:event_StornoButton1ActionPerformed

    private void PridajFilmButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajFilmButton1ActionPerformed
        

        Film film = new Film();
        int dlzka=this.dlzka;
        Date premiera = this.premiera;
        URL recenzia = this.recenzia;
        URL trailer= this.trailer;
        String obsah= this.obsah;
        int hodnotenie;
        String kont2 = HodnotenieTextField1.getText();
        if (kont2.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste hodnotenie!");
            return;
        } else {
            hodnotenie = Integer.parseInt(HodnotenieTextField1.getText());
        }
        film.setHodnotenie(hodnotenie);

        String nazov = NazovTextField1.getText();
        if (nazov.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste nazov!");
            return;
        }
        film.setNazov(nazov);     
        film.setDlzka(dlzka);
        film.setObsah(obsah);
        film.setTrailer(trailer);
        film.setPremiera(premiera);
        film.setRecenzia(recenzia);
        sqlfilm.pridat(film);
        int id = sqlfilm.idecko(film.getNazov());
        StatDao sqlstat = StatDaoFactory.INSTANCE.getStatDao();
        HerecDao sqlherec = HerecDaoFactory.INSTANCE.getHerecDao();
        ZanerDao sqlzaner = ZanerDaoFactory.INSTANCE.getZanerDao();
        ScenaristaDao sqlscenarista = ScenaristaDaoFactory.INSTANCE.getScenaristaDao();
        ReziserDao sqlreziser = ReziserDaoFactory.INSTANCE.getReziserDao();
        System.out.println(reziseri.toString());
        for (Herec herec : herci) {
            herec.setId(id);
            sqlherec.pridat(herec);
        }
        for (Stat stat : staty) {
            stat.setId(id);
            sqlstat.pridat(stat);
        }
        for (Zaner zaner : zanre) {
            zaner.setId(id);
            sqlzaner.pridat(zaner);
        }
        for (Scenarista scenarista : scenaristi) {
            scenarista.setId(id);
            sqlscenarista.pridat(scenarista);
        }

        for (Reziser reziser : reziseri) {
            reziser.setId(id);
            sqlreziser.pridat(reziser);
        }
        JOptionPane.showMessageDialog(null, "Film bol uspesne pridany");
        this.setVisible(false);
    }//GEN-LAST:event_PridajFilmButton1ActionPerformed

    private void HodnotenieTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HodnotenieTextField1KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_HodnotenieTextField1KeyTyped

    private void ZmazScenaristuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZmazScenaristuButton1ActionPerformed
        Scenarista scenarista = (Scenarista) ScenaristaList1.getSelectedValue();
        scenaristi.remove(scenarista);
        refreshScenaristi();
    }//GEN-LAST:event_ZmazScenaristuButton1ActionPerformed

    private void PridajScenaristuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajScenaristuButton1ActionPerformed
        PridajScenaristuForm.setVisible(true);
    }//GEN-LAST:event_PridajScenaristuButton1ActionPerformed

    private void ZmazReziseraButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZmazReziseraButton1ActionPerformed
        Reziser reziser = (Reziser) ReziserList1.getSelectedValue();
        reziseri.remove(reziser);
        refreshReziseri();
    }//GEN-LAST:event_ZmazReziseraButton1ActionPerformed

    private void PridajReziseraButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajReziseraButton1ActionPerformed
        PridajReziseraForm.setVisible(true);
    }//GEN-LAST:event_PridajReziseraButton1ActionPerformed

    private void ZmazStatButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZmazStatButton1ActionPerformed
        Stat stat = (Stat) StatyList1.getSelectedValue();
        staty.remove(stat);
        refreshStaty();
    }//GEN-LAST:event_ZmazStatButton1ActionPerformed

    private void PridajStatButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajStatButton1ActionPerformed
       PridajStatForm.setVisible(true);
    }//GEN-LAST:event_PridajStatButton1ActionPerformed

    private void ZmazZanerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZmazZanerButton1ActionPerformed
        Zaner zaner = (Zaner) ZanreList1.getSelectedValue();
        zanre.remove(zaner);
        refreshZanre();
    }//GEN-LAST:event_ZmazZanerButton1ActionPerformed

    private void PridajZanerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajZanerButton1ActionPerformed
        PridajZanerForm.setVisible(true);
    }//GEN-LAST:event_PridajZanerButton1ActionPerformed

    private void ZmazHercaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZmazHercaButton1ActionPerformed
        Herec herec = (Herec) HerciList1.getSelectedValue();
        herci.remove(herec);
        refreshHerci();
    }//GEN-LAST:event_ZmazHercaButton1ActionPerformed

    private void PridajHercaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajHercaButton1ActionPerformed
        PridajHercaForm.setVisible(true);
        
    }//GEN-LAST:event_PridajHercaButton1ActionPerformed

    private void PridajHercaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajHercaButtonActionPerformed
       Herec herec = new Herec();

        String meno = MenoHercaForm.getText();
        if (meno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste meno herca!");
            return;
        }
        herec.setMeno(meno);
        URL wiki = null;
        try {
            wiki = new URL(ZivotopisHercaForm.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmFormCisto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (wiki == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zivotopis!");
            return;
        }
        herec.setWiki(wiki);

        herci.add(herec);
        refreshHerci();
        ZivotopisHercaForm.setText("");
        MenoHercaForm.setText("");
        PridajHercaForm.setVisible(false);
    }//GEN-LAST:event_PridajHercaButtonActionPerformed

    private void ZrusHercaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZrusHercaButtonActionPerformed
        PridajHercaForm.setVisible(false);
    }//GEN-LAST:event_ZrusHercaButtonActionPerformed

    private void PridajStatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajStatButtonActionPerformed
         Stat stat = new Stat();

        String menoStatu = StatyTextField.getText();
        if (menoStatu.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste stat!");
            return;
        }

        stat.setNazov(menoStatu);
        staty.add(stat);
        refreshStaty();
        StatyTextField.setText("");
        PridajStatForm.setVisible(false);
    }//GEN-LAST:event_PridajStatButtonActionPerformed

    private void ZrusHercaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZrusHercaButton1ActionPerformed
        PridajStatForm.setVisible(false);
    }//GEN-LAST:event_ZrusHercaButton1ActionPerformed

    private void PridajZanerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajZanerButtonActionPerformed
Zaner zaner = new Zaner();

        String menoZanra = ZanerTextField.getText();
        if (menoZanra.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zaner!");
            return;
        }

        zaner.setMeno(menoZanra);
        zanre.add(zaner);
        refreshZanre();
        ZanerTextField.setText(""); 
         PridajZanerForm.setVisible(false);
    }//GEN-LAST:event_PridajZanerButtonActionPerformed

    private void ZrusZanerFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZrusZanerFormButtonActionPerformed
     PridajZanerForm.setVisible(false);
    }//GEN-LAST:event_ZrusZanerFormButtonActionPerformed

    private void PridajScenaristuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajScenaristuButtonActionPerformed
  Scenarista scenarista = new Scenarista();

        String meno = MenoScenaristuTextfield.getText();
        if (meno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste meno scenaristu!");
            return;
        }
        scenarista.setMeno(meno);
        URL wiki = null;
        try {
            wiki = new URL(ZivotopisScenaristuTextField.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmFormCisto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (wiki == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zivotopis!");
            return;
        }
        scenarista.setWiki(wiki);

        scenaristi.add(scenarista);
        refreshScenaristi();
        MenoScenaristuTextfield.setText("");
        ZivotopisScenaristuTextField.setText("");
        PridajScenaristuForm.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_PridajScenaristuButtonActionPerformed

    private void ZrusScenaristuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZrusScenaristuButtonActionPerformed
PridajScenaristuForm.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_ZrusScenaristuButtonActionPerformed

    private void PridajReziseraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajReziseraButtonActionPerformed
       Reziser reziser = new Reziser();

        String meno = MenoReziseraTextField.getText();
        if (meno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste meno rezisera!");
            return;
        }
        reziser.setMeno(meno);
        URL wiki = null;
        try {
            wiki = new URL(ZivotopisReziseraTextField.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmFormCisto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (wiki == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zivotopis!");
            return;
        }
        reziser.setWiki(wiki);

        reziseri.add(reziser);
        refreshReziseri();
        MenoReziseraTextField.setText("");
        ZivotopisReziseraTextField.setText("");
        PridajReziseraForm.setVisible(false);
    }//GEN-LAST:event_PridajReziseraButtonActionPerformed

    private void ZrusReziseraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZrusReziseraButtonActionPerformed
    PridajReziseraForm.setVisible(false);
    }//GEN-LAST:event_ZrusReziseraButtonActionPerformed

    private void PridajRecenziuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajRecenziuButtonActionPerformed
         URL recenzia = null;
        try {
            recenzia = new URL(RecenziaTextField.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmFormCisto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (recenzia == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste recenziu!");
            return;
        }
        this.recenzia=recenzia;
        RecenziaTextField.setText("");
        PridajRecenziuForm.setVisible(false);
    }//GEN-LAST:event_PridajRecenziuButtonActionPerformed

    private void ZrusRecenziuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZrusRecenziuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZrusRecenziuButtonActionPerformed

    private void PridajDlzkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajDlzkuButtonActionPerformed
         int dlzka;
        String kont3 = DlzkaTextField.getText();
        if (kont3.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste dlzku filmu!");
            return;
        } else {
            dlzka = Integer.parseInt(DlzkaTextField.getText());
        }
        this.dlzka=dlzka;
        PridajDlzkuForm.setVisible(false);
        DlzkaTextField.setText("");
    }//GEN-LAST:event_PridajDlzkuButtonActionPerformed

    private void ZrusDlzkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZrusDlzkuButtonActionPerformed
       PridajDlzkuButton.setVisible(false);
    }//GEN-LAST:event_ZrusDlzkuButtonActionPerformed

    private void ZrusObsahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZrusObsahButtonActionPerformed
        PridajObsahForm.setVisible(false);
    }//GEN-LAST:event_ZrusObsahButtonActionPerformed

    private void PridajObsahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajObsahButtonActionPerformed
        String obsah = ObsahTextArea.getText();
        if (obsah.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste obsah!");
            return;
        }
        this.obsah=obsah;
        PridajObsahForm.setVisible(false);
        ObsahTextArea.setText("");
    }//GEN-LAST:event_PridajObsahButtonActionPerformed

    private void PridajTrailerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajTrailerButtonActionPerformed
        URL trailer = null;
        try {
            trailer = new URL(TrailerTextField.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmFormCisto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (trailer == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste trailer!");
            return;
        }
        this.trailer=trailer;
        PridajTrailerForm.setVisible(false);
        TrailerTextField.setText("");
    }//GEN-LAST:event_PridajTrailerButtonActionPerformed

    private void ZrusTrailerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZrusTrailerButtonActionPerformed
       PridajTrailerForm.setVisible(false);
    }//GEN-LAST:event_ZrusTrailerButtonActionPerformed

    private void PridajRecenziuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajRecenziuActionPerformed
        PridajRecenziuForm.setVisible(true);
    }//GEN-LAST:event_PridajRecenziuActionPerformed

    private void PridajPRemieruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajPRemieruButtonActionPerformed
        PridajPremieruForm.setVisible(true);
    }//GEN-LAST:event_PridajPRemieruButtonActionPerformed

    private void PridajObsahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajObsahActionPerformed
       PridajObsahForm.setVisible(true);
    }//GEN-LAST:event_PridajObsahActionPerformed

    private void PridajTrailerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajTrailerButton1ActionPerformed
        PridajTrailerForm.setVisible(true);
    }//GEN-LAST:event_PridajTrailerButton1ActionPerformed

    private void PridajDlzku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajDlzku1ActionPerformed
        PridajDlzkuForm.setVisible(true);
    }//GEN-LAST:event_PridajDlzku1ActionPerformed

    private void ZrusPremieruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZrusPremieruButtonActionPerformed
        PridajPremieruForm.setVisible(false);
    }//GEN-LAST:event_ZrusPremieruButtonActionPerformed

    private void pridajPremieruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajPremieruButtonActionPerformed
        Date datum = null;
        
        DateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {

            datum = sdf.parse(rokTextField.getText()+"-"+mesiacTextField.getText()+"-"+denTextField.getText());
         
        } catch (ParseException ex) {
            Logger.getLogger(PridatFilmFormCisto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (datum == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste premieru!");
            return;
        }

        this.premiera=datum;
        rokTextField.setText("");
        mesiacTextField.setText("");
        denTextField.setText("");
        PridajPremieruForm.setVisible(false);
    }//GEN-LAST:event_pridajPremieruButtonActionPerformed

    private void rokTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rokTextFieldKeyTyped
 char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_rokTextFieldKeyTyped

    private void mesiacTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesiacTextFieldKeyTyped
 char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mesiacTextFieldKeyTyped

    private void denTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_denTextFieldKeyTyped
 char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_denTextFieldKeyTyped

    private void PridajDlzkuFormKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PridajDlzkuFormKeyTyped
 char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_PridajDlzkuFormKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PridatFilmFormCisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PridatFilmFormCisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PridatFilmFormCisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PridatFilmFormCisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PridatFilmFormCisto dialog = new PridatFilmFormCisto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DenLabel;
    private javax.swing.JTextField DlzkaTextField;
    private javax.swing.JLabel HerciLabel2;
    private javax.swing.JList HerciList1;
    private javax.swing.JLabel HodnotenieLabel2;
    private javax.swing.JTextField HodnotenieTextField1;
    private javax.swing.JTextField MenoHercaForm;
    private javax.swing.JTextField MenoReziseraTextField;
    private javax.swing.JTextField MenoScenaristuTextfield;
    private javax.swing.JLabel MesiacLabel;
    private javax.swing.JLabel NazovLabel1;
    private javax.swing.JTextField NazovTextField1;
    private javax.swing.JLabel ObsahLabel;
    private javax.swing.JTextArea ObsahTextArea;
    private javax.swing.JButton PridajDlzku1;
    private javax.swing.JToggleButton PridajDlzkuButton;
    private javax.swing.JFrame PridajDlzkuForm;
    private javax.swing.JButton PridajFilmButton1;
    private javax.swing.JToggleButton PridajHercaButton;
    private javax.swing.JButton PridajHercaButton1;
    private javax.swing.JFrame PridajHercaForm;
    private javax.swing.JButton PridajObsah;
    private javax.swing.JToggleButton PridajObsahButton;
    private javax.swing.JFrame PridajObsahForm;
    private javax.swing.JButton PridajPRemieruButton;
    private javax.swing.JFrame PridajPremieruForm;
    private javax.swing.JButton PridajRecenziu;
    private javax.swing.JToggleButton PridajRecenziuButton;
    private javax.swing.JFrame PridajRecenziuForm;
    private javax.swing.JToggleButton PridajReziseraButton;
    private javax.swing.JButton PridajReziseraButton1;
    private javax.swing.JFrame PridajReziseraForm;
    private javax.swing.JToggleButton PridajScenaristuButton;
    private javax.swing.JButton PridajScenaristuButton1;
    private javax.swing.JFrame PridajScenaristuForm;
    private javax.swing.JToggleButton PridajStatButton;
    private javax.swing.JButton PridajStatButton1;
    private javax.swing.JFrame PridajStatForm;
    private javax.swing.JToggleButton PridajTrailerButton;
    private javax.swing.JButton PridajTrailerButton1;
    private javax.swing.JFrame PridajTrailerForm;
    private javax.swing.JToggleButton PridajZanerButton;
    private javax.swing.JButton PridajZanerButton1;
    private javax.swing.JFrame PridajZanerForm;
    private javax.swing.JLabel RecenziaLabel;
    private javax.swing.JLabel RecenziaLabel2;
    private javax.swing.JTextField RecenziaTextField;
    private javax.swing.JLabel ReziserLabel1;
    private javax.swing.JList ReziserList1;
    private javax.swing.JLabel ScenaristaLabel2;
    private javax.swing.JList ScenaristaList1;
    private javax.swing.JLabel StatLabel1;
    private javax.swing.JList StatyList1;
    private javax.swing.JTextField StatyTextField;
    private javax.swing.JButton StornoButton1;
    private javax.swing.JTextField TrailerTextField;
    private javax.swing.JTextField ZanerTextField;
    private javax.swing.JLabel ZanreLabel1;
    private javax.swing.JList ZanreList1;
    private javax.swing.JTextField ZivotopisHercaForm;
    private javax.swing.JTextField ZivotopisReziseraTextField;
    private javax.swing.JTextField ZivotopisScenaristuTextField;
    private javax.swing.JButton ZmazHercaButton1;
    private javax.swing.JButton ZmazReziseraButton1;
    private javax.swing.JButton ZmazScenaristuButton1;
    private javax.swing.JButton ZmazStatButton1;
    private javax.swing.JButton ZmazZanerButton1;
    private javax.swing.JToggleButton ZrusDlzkuButton;
    private javax.swing.JToggleButton ZrusHercaButton;
    private javax.swing.JToggleButton ZrusHercaButton1;
    private javax.swing.JToggleButton ZrusObsahButton;
    private javax.swing.JToggleButton ZrusPremieruButton;
    private javax.swing.JToggleButton ZrusRecenziuButton;
    private javax.swing.JToggleButton ZrusReziseraButton;
    private javax.swing.JToggleButton ZrusScenaristuButton;
    private javax.swing.JToggleButton ZrusTrailerButton;
    private javax.swing.JToggleButton ZrusZanerFormButton;
    private javax.swing.JTextField denTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField mesiacTextField;
    private javax.swing.JToggleButton pridajPremieruButton;
    private javax.swing.JLabel rokLabel;
    private javax.swing.JTextField rokTextField;
    // End of variables declaration//GEN-END:variables

    private void refreshHerci() {
        HerciList1.setListData(this.herci.toArray());
    }

    private void refreshStaty() {
        StatyList1.setListData(this.staty.toArray());
    }

    private void refreshZanre() {
        ZanreList1.setListData(this.zanre.toArray());
    }

    private void refreshReziseri() {
        ReziserList1.setListData(this.reziseri.toArray());
    }

    private void refreshScenaristi() {
        ScenaristaList1.setListData(this.scenaristi.toArray());
    }

}
