/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package okno;


import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import kniznica.*;

/**
 *
 * @author Matúš
 */
public class PridatFilmFormCisto extends javax.swing.JFrame {
    private FilmDao sqlfilm = FilmDaoFactory.INSTANCE.getFilmDao();
    private Film film;
    private Set<Herec>herci= new HashSet<>();
    private Set<Stat> staty = new HashSet<>();
    private  Set<Zaner> zanre = new HashSet<>();
    private Set<Reziser> reziseri = new HashSet<>();
    private Set<Scenarista> scenaristi = new HashSet<>();
    private int id= sqlfilm.idecko();
    
    
    /**
     * Creates new form PridatFilmFormCisto
     */
    public PridatFilmFormCisto(java.awt.Frame parent, boolean modal) {
        initComponents();
        
    }
    
    PridatFilmFormCisto(Frame parent, boolean modal, Film film) {
      //  super(parent, modal);
        initComponents();
        refreshHerci();
        refreshZanre();
        setLocationRelativeTo(null);
        
        this.film = film;        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        HerciLabel2 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        HerciList1 = new javax.swing.JList();
        ZanreLabel1 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        ZanreList1 = new javax.swing.JList();
        StatLabel1 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        StatyList1 = new javax.swing.JList();
        RecenziaLabel1 = new javax.swing.JLabel();
        RecenziaTextField1 = new javax.swing.JTextField();
        TrailerLabel1 = new javax.swing.JLabel();
        TrailerTextField1 = new javax.swing.JTextField();
        PridajHercaButton1 = new javax.swing.JButton();
        ZmazHercaButton1 = new javax.swing.JButton();
        PridajZanerButton1 = new javax.swing.JButton();
        ZmazZanerButton1 = new javax.swing.JButton();
        PridajStatButton1 = new javax.swing.JButton();
        ZmazStatButton1 = new javax.swing.JButton();
        PridajReziseraButton1 = new javax.swing.JButton();
        ZmazReziseraButton1 = new javax.swing.JButton();
        PridajScenaristuButton1 = new javax.swing.JButton();
        ZmazScenaristuButton1 = new javax.swing.JButton();
        mesiac1 = new javax.swing.JTextField();
        den1 = new javax.swing.JTextField();
        RokLabel1 = new javax.swing.JLabel();
        MesiacLabel1 = new javax.swing.JLabel();
        DenLabel1 = new javax.swing.JLabel();
        PremieraLabel1 = new javax.swing.JLabel();
        rokTextField1 = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        ObsahTextArea1 = new javax.swing.JTextArea();
        DlzkaLabel1 = new javax.swing.JLabel();
        DlzkaTextField1 = new javax.swing.JTextField();
        ObsahLabel1 = new javax.swing.JLabel();
        HodnotenieTextField1 = new javax.swing.JTextField();
        NazovTextField1 = new javax.swing.JTextField();
        HodnotenieLabel2 = new javax.swing.JLabel();
        NazovLabel1 = new javax.swing.JLabel();
        MenoHercaTextField = new javax.swing.JTextField();
        HercovZivotopisTextField1 = new javax.swing.JTextField();
        HerciLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ZanerTextField1 = new javax.swing.JTextField();
        NazovZanruLabel1 = new javax.swing.JLabel();
        StatyTextField1 = new javax.swing.JTextField();
        StatyLabel1 = new javax.swing.JLabel();
        ReziserTextField1 = new javax.swing.JTextField();
        RezZivTextField1 = new javax.swing.JTextField();
        HerciLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ScenZivTextField1 = new javax.swing.JTextField();
        ScenaristaTextField1 = new javax.swing.JTextField();
        ScenaristaLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PridajFilmButton1 = new javax.swing.JButton();
        StornoButton1 = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        ReziserList1 = new javax.swing.JList();
        ReziserLabel1 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        ScenaristaList1 = new javax.swing.JList();
        ScenaristaLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HerciLabel2.setText("Herci");

        HerciList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(HerciList1);

        ZanreLabel1.setText("Zanre");

        ZanreList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(ZanreList1);

        StatLabel1.setText("Staty");

        StatyList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(StatyList1);

        RecenziaLabel1.setText("Recenzia");

        TrailerLabel1.setText("Trailer");

        TrailerTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrailerTextField1ActionPerformed(evt);
            }
        });

        PridajHercaButton1.setText("PridajHerca");
        PridajHercaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajHercaButton1ActionPerformed(evt);
            }
        });

        ZmazHercaButton1.setText("ZmazHerca");
        ZmazHercaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZmazHercaButton1ActionPerformed(evt);
            }
        });

        PridajZanerButton1.setText("PridajZaner");
        PridajZanerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajZanerButton1ActionPerformed(evt);
            }
        });

        ZmazZanerButton1.setText("ZmazZaner");
        ZmazZanerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZmazZanerButton1ActionPerformed(evt);
            }
        });

        PridajStatButton1.setText("PridajStat");
        PridajStatButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajStatButton1ActionPerformed(evt);
            }
        });

        ZmazStatButton1.setText("ZmazStat");
        ZmazStatButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZmazStatButton1ActionPerformed(evt);
            }
        });

        PridajReziseraButton1.setText("PridajRezisera");
        PridajReziseraButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajReziseraButton1ActionPerformed(evt);
            }
        });

        ZmazReziseraButton1.setText("ZmazRezisera");
        ZmazReziseraButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZmazReziseraButton1ActionPerformed(evt);
            }
        });

        PridajScenaristuButton1.setText("PridajScenaristu");
        PridajScenaristuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajScenaristuButton1ActionPerformed(evt);
            }
        });

        ZmazScenaristuButton1.setText("ZmazScenaristu");
        ZmazScenaristuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZmazScenaristuButton1ActionPerformed(evt);
            }
        });

        mesiac1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesiac1KeyTyped(evt);
            }
        });

        den1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                den1KeyTyped(evt);
            }
        });

        RokLabel1.setText("yyyy");

        MesiacLabel1.setText("mm");

        DenLabel1.setText("dd");

        PremieraLabel1.setText("Premiera");

        rokTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rokTextField1KeyTyped(evt);
            }
        });

        ObsahTextArea1.setColumns(20);
        ObsahTextArea1.setRows(5);
        jScrollPane13.setViewportView(ObsahTextArea1);

        DlzkaLabel1.setText("Dlzka");

        DlzkaTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DlzkaTextField1KeyTyped(evt);
            }
        });

        ObsahLabel1.setText("Obsah");

        HodnotenieTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HodnotenieTextField1KeyTyped(evt);
            }
        });

        HodnotenieLabel2.setText("Hodnotenie");

        NazovLabel1.setText("Nazov");

        HerciLabel3.setText("MenoHerca");

        jLabel7.setText("HercovZiv.");

        NazovZanruLabel1.setText("NazovZanru");

        StatyLabel1.setText("NazovStatu");

        HerciLabel5.setText("MenoRezisera");

        jLabel11.setText("ReziserovZiv.");

        ScenaristaLabel1.setText("MenoScenaristu");

        jLabel12.setText("ScenaristovZiv.");

        PridajFilmButton1.setText("PridajFilm");
        PridajFilmButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajFilmButton1ActionPerformed(evt);
            }
        });

        StornoButton1.setText("Storno");
        StornoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StornoButton1ActionPerformed(evt);
            }
        });

        ReziserList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane14.setViewportView(ReziserList1);

        ReziserLabel1.setText("Reziser");

        ScenaristaList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane15.setViewportView(ScenaristaList1);

        ScenaristaLabel2.setText("Scenarista");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NazovTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGap(191, 191, 191)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(StatyLabel1)
                                                .addComponent(StatyTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(HerciLabel3)
                                                .addComponent(MenoHercaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7)
                                                .addComponent(HercovZivotopisTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ZanerTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(NazovZanruLabel1)))))
                                .addGap(39, 39, 39)
                                .addComponent(HodnotenieTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(RecenziaLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RecenziaTextField1))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PremieraLabel1)
                                            .addComponent(DlzkaLabel1))
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rokTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(RokLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(mesiac1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(den1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(MesiacLabel1)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(DenLabel1)
                                                        .addGap(53, 53, 53)
                                                        .addComponent(ObsahLabel1))))
                                            .addComponent(DlzkaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(TrailerLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TrailerTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(PridajFilmButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(StornoButton1))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ScenaristaLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(NazovLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HodnotenieLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(StatLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ZanreLabel1)
                                    .addComponent(HerciLabel2)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ReziserLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HerciLabel5)
                                    .addComponent(ReziserTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RezZivTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(ScenaristaLabel1)
                                    .addComponent(ScenaristaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(ScenZivTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ZmazZanerButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ZmazHercaButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PridajZanerButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PridajStatButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PridajReziseraButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ZmazReziseraButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PridajScenaristuButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ZmazStatButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PridajHercaButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ZmazScenaristuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NazovLabel1)
                    .addComponent(NazovTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HodnotenieLabel2)
                    .addComponent(HodnotenieTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HerciLabel2)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(PridajHercaButton1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ZanreLabel1)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NazovZanruLabel1)
                                        .addComponent(PridajZanerButton1)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ZanerTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ZmazZanerButton1)))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PridajStatButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ZmazStatButton1))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(StatyLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(StatyTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(StatLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(HerciLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(MenoHercaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HercovZivotopisTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZmazHercaButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReziserLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PridajReziseraButton1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(HerciLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReziserTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RezZivTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZmazReziseraButton1))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScenaristaLabel2)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PridajScenaristuButton1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ScenaristaLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ScenaristaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ScenZivTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ZmazScenaristuButton1))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RokLabel1)
                            .addComponent(MesiacLabel1)
                            .addComponent(DenLabel1)
                            .addComponent(ObsahLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PremieraLabel1)
                            .addComponent(rokTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesiac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(den1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DlzkaLabel1)
                            .addComponent(DlzkaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RecenziaLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RecenziaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TrailerLabel1)
                        .addComponent(TrailerTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PridajFilmButton1)
                    .addComponent(StornoButton1))
                .addGap(147, 147, 147))
        );

        jScrollPane7.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PridajFilmButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajFilmButton1ActionPerformed
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-mm-dd");
        
        Film film = new Film();
       
        System.out.println(id);
        film.setId(id);
        
        int hodnotenie;
        String kont2 = HodnotenieTextField1.getText();
        if (kont2.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste hodnotenie!");
            return;
        } else {
            hodnotenie = Integer.parseInt(HodnotenieTextField1.getText());
        }        
        film.setHodnotenie(hodnotenie);
        
        String nazov = NazovTextField1.getText();
        if (nazov.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste nazov!");
            return;
        }        
        film.setNazov(nazov);
        
        
        int dlzka;
        String kont3 = DlzkaTextField1.getText();
        if (kont3.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste dlzku filmu!");
            return;
        } else {
            dlzka = Integer.parseInt(DlzkaTextField1.getText());
        }        
        film.setDlzka(dlzka);
        
        
        Date datum = null;
        try {
            datum = sdf.parse(rokTextField1.getText()+"-"+mesiac1.getText()+"-"+den1.getText());
        } catch (ParseException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (datum == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste premieru!");
            return;
        }        
        film.setPremiera(datum);
        
        String obsah = ObsahTextArea1.getText();
        if (obsah.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste obsah!");
            return;
        }        
        
        film.setObsah(obsah);
        URL trailer = null;
        try {
            trailer = new URL(TrailerTextField1.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (trailer == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste trailer!");
            return;
        }        
        film.setTrailer(trailer);        
        
        URL recenzia = null;
        try {
            recenzia = new URL(RecenziaTextField1.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (recenzia == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste recenziu!");
            return;
        }        
        film.setRecenzia(recenzia);
        
        
        sqlfilm.pridat(film);
        StatDao sqlstat = StatDaoFactory.INSTANCE.getStatDao();
        HerecDao sqlherec = HerecDaoFactory.INSTANCE.getHerecDao();
        ZanerDao sqlzaner = ZanerDaoFactory.INSTANCE.getZanerDao();
        ScenaristaDao sqlscenarista = ScenaristaDaoFactory.INSTANCE.getScenaristaDao();
        ReziserDao sqlreziser = ReziserDaoFactory.INSTANCE.getReziserDao();
        System.out.println(reziseri.toString());
        for (Herec herec : herci) {
            sqlherec.pridat(herec);
        }
        for (Stat stat : staty) {
            sqlstat.pridat(stat);
        }
        for (Zaner zaner : zanre) {
            sqlzaner.pridat(zaner);
        }
        for(Scenarista scenarista:scenaristi){
        sqlscenarista.pridat(scenarista);}
       
        for(Reziser reziser : reziseri){
        sqlreziser.pridat(reziser);}
        JOptionPane.showMessageDialog(null,"Film bol uspesne pridany");
         this.setVisible(false);
    }//GEN-LAST:event_PridajFilmButton1ActionPerformed

    private void HodnotenieTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HodnotenieTextField1KeyTyped
         char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_HodnotenieTextField1KeyTyped

    private void DlzkaTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DlzkaTextField1KeyTyped
         char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_DlzkaTextField1KeyTyped

    private void rokTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rokTextField1KeyTyped
       char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_rokTextField1KeyTyped

    private void den1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_den1KeyTyped
         char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_den1KeyTyped

    private void mesiac1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesiac1KeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_mesiac1KeyTyped

    private void TrailerTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrailerTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrailerTextField1ActionPerformed

    private void StornoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StornoButton1ActionPerformed
        this.setVisible(false);
       this.disable();
    }//GEN-LAST:event_StornoButton1ActionPerformed

    private void PridajZanerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajZanerButton1ActionPerformed
       Zaner zaner = new Zaner();
       
        String menoZanra = ZanerTextField1.getText();
        if (menoZanra.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zaner!");
            return;
        } 
        
        zaner.setId(id);
        zaner.setMeno(menoZanra);
        zanre.add(zaner);
        refreshZanre();
        ZanerTextField1.setText("");
    }//GEN-LAST:event_PridajZanerButton1ActionPerformed

    private void ZmazZanerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZmazZanerButton1ActionPerformed
        Zaner zaner = (Zaner) ZanreList1.getSelectedValue();
        zanre.remove(zaner);
        refreshZanre();
    }//GEN-LAST:event_ZmazZanerButton1ActionPerformed

    private void PridajHercaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajHercaButton1ActionPerformed
      Herec herec = new Herec();
        herec.setId(id);
        String meno = MenoHercaTextField.getText();
        if (meno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste meno herca!");
            return;
        }
        herec.setMeno(meno);
        URL wiki = null;
        try {
            wiki = new URL(HercovZivotopisTextField1.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (wiki == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zivotopis!");
            return;
        }
        herec.setWiki(wiki);

        herci.add(herec);
        refreshHerci();
        HercovZivotopisTextField1.setText("");
        MenoHercaTextField.setText("");
    }//GEN-LAST:event_PridajHercaButton1ActionPerformed

    private void ZmazHercaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZmazHercaButton1ActionPerformed
       Herec herec = (Herec) HerciList1.getSelectedValue();
        herci.remove(herec);
        refreshHerci();
    }//GEN-LAST:event_ZmazHercaButton1ActionPerformed

    private void PridajStatButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajStatButton1ActionPerformed
       Stat stat = new Stat();
      
      String menoStatu =StatyTextField1.getText();
        if (menoStatu.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste stat!");
            return;
        } 
        
        stat.setId(id);
        stat.setNazov(menoStatu);
        staty.add(stat);
        refreshStaty();
        StatyTextField1.setText("");
    }//GEN-LAST:event_PridajStatButton1ActionPerformed

    private void ZmazStatButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZmazStatButton1ActionPerformed
        Stat stat = (Stat) StatyList1.getSelectedValue();
        staty.remove(stat);
        refreshStaty();
    }//GEN-LAST:event_ZmazStatButton1ActionPerformed

    private void PridajReziseraButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajReziseraButton1ActionPerformed
        Reziser reziser = new Reziser();

String meno = ReziserTextField1.getText();
        if (meno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste meno rezisera!");
            return;
        } 
reziser.setMeno(meno);
URL wiki = null;
        try {
            wiki = new URL(RezZivTextField1.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (wiki == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zivotopis!");
            return;
        }        
        reziser.setWiki(wiki);
        reziser.setId(id);
        reziseri.add(reziser);
        refreshReziseri();
        ReziserTextField1.setText("");
        RezZivTextField1.setText("");
    }//GEN-LAST:event_PridajReziseraButton1ActionPerformed

    private void ZmazReziseraButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZmazReziseraButton1ActionPerformed
Reziser reziser = (Reziser)  ReziserList1.getSelectedValue();
        reziseri.remove(reziser);
        refreshReziseri();
    }//GEN-LAST:event_ZmazReziseraButton1ActionPerformed

    private void PridajScenaristuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajScenaristuButton1ActionPerformed
         Scenarista scenarista = new Scenarista();

String meno = ScenaristaTextField1.getText();
        if (meno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste meno scenaristu!");
            return;
        } 
scenarista.setMeno(meno);
URL wiki = null;
        try {
            wiki = new URL(ScenZivTextField1.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (wiki == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zivotopis!");
            return;
        }        
        scenarista.setWiki(wiki);
        scenarista.setId(id);
        scenaristi.add(scenarista);
        refreshScenaristi();
    }//GEN-LAST:event_PridajScenaristuButton1ActionPerformed

    private void ZmazScenaristuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZmazScenaristuButton1ActionPerformed
       Scenarista scenarista = (Scenarista) ScenaristaList1.getSelectedValue();
        scenaristi.remove(scenarista);
        refreshScenaristi();
    }//GEN-LAST:event_ZmazScenaristuButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PridatFilmFormCisto dialog = new PridatFilmFormCisto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DenLabel1;
    private javax.swing.JLabel DlzkaLabel1;
    private javax.swing.JTextField DlzkaTextField1;
    private javax.swing.JLabel HerciLabel2;
    private javax.swing.JLabel HerciLabel3;
    private javax.swing.JLabel HerciLabel5;
    private javax.swing.JList HerciList1;
    private javax.swing.JTextField HercovZivotopisTextField1;
    private javax.swing.JLabel HodnotenieLabel2;
    private javax.swing.JTextField HodnotenieTextField1;
    private javax.swing.JTextField MenoHercaTextField;
    private javax.swing.JLabel MesiacLabel1;
    private javax.swing.JLabel NazovLabel1;
    private javax.swing.JTextField NazovTextField1;
    private javax.swing.JLabel NazovZanruLabel1;
    private javax.swing.JLabel ObsahLabel1;
    private javax.swing.JTextArea ObsahTextArea1;
    private javax.swing.JLabel PremieraLabel1;
    private javax.swing.JButton PridajFilmButton1;
    private javax.swing.JButton PridajHercaButton1;
    private javax.swing.JButton PridajReziseraButton1;
    private javax.swing.JButton PridajScenaristuButton1;
    private javax.swing.JButton PridajStatButton1;
    private javax.swing.JButton PridajZanerButton1;
    private javax.swing.JLabel RecenziaLabel1;
    private javax.swing.JTextField RecenziaTextField1;
    private javax.swing.JTextField RezZivTextField1;
    private javax.swing.JLabel ReziserLabel1;
    private javax.swing.JList ReziserList1;
    private javax.swing.JTextField ReziserTextField1;
    private javax.swing.JLabel RokLabel1;
    private javax.swing.JTextField ScenZivTextField1;
    private javax.swing.JLabel ScenaristaLabel1;
    private javax.swing.JLabel ScenaristaLabel2;
    private javax.swing.JList ScenaristaList1;
    private javax.swing.JTextField ScenaristaTextField1;
    private javax.swing.JLabel StatLabel1;
    private javax.swing.JLabel StatyLabel1;
    private javax.swing.JList StatyList1;
    private javax.swing.JTextField StatyTextField1;
    private javax.swing.JButton StornoButton1;
    private javax.swing.JLabel TrailerLabel1;
    private javax.swing.JTextField TrailerTextField1;
    private javax.swing.JTextField ZanerTextField1;
    private javax.swing.JLabel ZanreLabel1;
    private javax.swing.JList ZanreList1;
    private javax.swing.JButton ZmazHercaButton1;
    private javax.swing.JButton ZmazReziseraButton1;
    private javax.swing.JButton ZmazScenaristuButton1;
    private javax.swing.JButton ZmazStatButton1;
    private javax.swing.JButton ZmazZanerButton1;
    private javax.swing.JTextField den1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField mesiac1;
    private javax.swing.JTextField rokTextField1;
    // End of variables declaration//GEN-END:variables

    private void refreshHerci() {
         HerciList1.setListData(this.herci.toArray());
    }

    private void refreshStaty() {
       StatyList1.setListData(this.staty.toArray());
    }
    
    private void refreshZanre() {
         ZanreList1.setListData(this.zanre.toArray());
    }

    private void refreshReziseri() {
        ReziserList1.setListData(this.reziseri.toArray());
    }

    private void refreshScenaristi() {
        ScenaristaList1.setListData(this.scenaristi.toArray());
    }

    
}
