/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package okno;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import kniznica.*;

/**
 *
 * @author Matúš
 */
public class PridatFilmForm extends javax.swing.JFrame {

    private Film film;
    private Set<Herec>herci= new HashSet<>();
   private Set<Stat> staty = new HashSet<>();
  private  Set<Zaner> zanre = new HashSet<>();
  private Set<Reziser> reziseri = new HashSet<>();
  private Set<Scenarista> scenaristi = new HashSet<>();
  private int id;
    //private FilmDao filmDao = FilmDaoFactory.instance.GetFilmDao();
    

    /**
     * Creates new form PridatFilmForm
     */
    public PridatFilmForm(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();

        
    }
    
    PridatFilmForm(Frame parent, boolean modal, Film film) {
      //  super(parent, modal);
        initComponents();
        refreshHerci();
        refreshZanre();
        setLocationRelativeTo(null);
        
        this.film = film;        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollBar1 = new javax.swing.JScrollBar();
        HodnotenieTextField = new javax.swing.JTextField();
        NazovTextField = new javax.swing.JTextField();
        HodnotenieLabel = new javax.swing.JLabel();
        NazovLabel = new javax.swing.JLabel();
        HerciLabel = new javax.swing.JLabel();
        ZanerLabel = new javax.swing.JLabel();
        DlzkaLabel = new javax.swing.JLabel();
        DlzkaTextField = new javax.swing.JTextField();
        PremieraLabel = new javax.swing.JLabel();
        rokTextField = new javax.swing.JTextField();
        StatLabel = new javax.swing.JLabel();
        ObsahLabel = new javax.swing.JLabel();
        TrailerLabel = new javax.swing.JLabel();
        TrailerTextField = new javax.swing.JTextField();
        RecenziaLabel = new javax.swing.JLabel();
        RecenziaTextField = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObsahTextArea = new javax.swing.JTextArea();
        mesiac = new javax.swing.JTextField();
        den = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menoHercaTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hercovZivotopiTextField1 = new javax.swing.JTextField();
        pridajHercaButton1 = new javax.swing.JButton();
        zmazHercaButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        zoznamHercovList1 = new javax.swing.JList();
        zanerTextField1 = new javax.swing.JTextField();
        pridajButton2 = new javax.swing.JButton();
        zmazZanerButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        zoznamZanreList = new javax.swing.JList();
        pridajStatTextField1 = new javax.swing.JTextField();
        pridajStatButton2 = new javax.swing.JButton();
        zmazStatButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        zoznamStatList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        reziserTextField1 = new javax.swing.JTextField();
        pridajReziseraButton1 = new javax.swing.JButton();
        zmazReziseraButton2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        zoznamReziserovList2 = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        scenaristaTextField1 = new javax.swing.JTextField();
        pridajScenaristuButton1 = new javax.swing.JButton();
        zmazScenaristuButton2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        zoznamScenaristovList3 = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        reziserWikiTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        scenaristaZivotopisTextField1 = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        HodnotenieTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HodnotenieTextFieldKeyTyped(evt);
            }
        });

        HodnotenieLabel.setText("Hodnotenie");

        NazovLabel.setText("Nazov");

        HerciLabel.setText("Meno herca");

        ZanerLabel.setText("Zaner");

        DlzkaLabel.setText("Dlzka");

        PremieraLabel.setText("Premiera");

        rokTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rokTextFieldActionPerformed(evt);
            }
        });

        StatLabel.setText("Stat");

        ObsahLabel.setText("Obsah");

        TrailerLabel.setText("Trailer");

        TrailerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrailerTextFieldActionPerformed(evt);
            }
        });

        RecenziaLabel.setText("Recenzia");

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ObsahTextArea.setColumns(20);
        ObsahTextArea.setRows(5);
        jScrollPane1.setViewportView(ObsahTextArea);

        jLabel1.setText("yyyy");

        jLabel2.setText("mm");

        jLabel3.setText("dd");

        menoHercaTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoHercaTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Hercov zivotopis");

        hercovZivotopiTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hercovZivotopiTextField1ActionPerformed(evt);
            }
        });

        pridajHercaButton1.setText("pridaj herca");
        pridajHercaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajHercaButton1ActionPerformed(evt);
            }
        });

        zmazHercaButton.setText("zmaz herca");
        zmazHercaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmazHercaButtonActionPerformed(evt);
            }
        });

        zoznamHercovList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(zoznamHercovList1);

        pridajButton2.setText("pridaj zaner");
        pridajButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajButton2ActionPerformed(evt);
            }
        });

        zmazZanerButton.setText("zmaz zaner");
        zmazZanerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmazZanerButtonActionPerformed(evt);
            }
        });

        zoznamZanreList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(zoznamZanreList);

        pridajStatButton2.setText("pridaj stat");
        pridajStatButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajStatButton2ActionPerformed(evt);
            }
        });

        zmazStatButton4.setText("zmaz stat");
        zmazStatButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmazStatButton4ActionPerformed(evt);
            }
        });

        zoznamStatList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(zoznamStatList);

        jLabel6.setText("Rezier");

        reziserTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reziserTextField1ActionPerformed(evt);
            }
        });

        pridajReziseraButton1.setText("pridaj rezisera");
        pridajReziseraButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajReziseraButton1ActionPerformed(evt);
            }
        });

        zmazReziseraButton2.setText("zmaz rezisera");
        zmazReziseraButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmazReziseraButton2ActionPerformed(evt);
            }
        });

        zoznamReziserovList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(zoznamReziserovList2);

        jLabel7.setText("Scenarista");

        pridajScenaristuButton1.setText("pridaj scenaristu");
        pridajScenaristuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajScenaristuButton1ActionPerformed(evt);
            }
        });

        zmazScenaristuButton2.setText("zmaz scenaristu");
        zmazScenaristuButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmazScenaristuButton2ActionPerformed(evt);
            }
        });

        zoznamScenaristovList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(zoznamScenaristovList3);

        jLabel8.setText("zivotopis");

        jLabel9.setText("zivotopis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HerciLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menoHercaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hercovZivotopiTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pridajHercaButton1)
                        .addGap(18, 18, 18)
                        .addComponent(zmazHercaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NazovLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NazovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HodnotenieLabel)
                        .addGap(18, 18, 18)
                        .addComponent(HodnotenieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StatLabel)
                        .addGap(48, 48, 48)
                        .addComponent(pridajStatTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pridajStatButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zmazStatButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PremieraLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rokTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mesiac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(den, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ZanerLabel)
                        .addGap(37, 37, 37)
                        .addComponent(zanerTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(pridajButton2)
                        .addGap(18, 18, 18)
                        .addComponent(zmazZanerButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(scenaristaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(scenaristaZivotopisTextField1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pridajScenaristuButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(zmazScenaristuButton2))
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(reziserTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(reziserWikiTextField1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pridajReziseraButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(zmazReziseraButton2))
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(OKButton)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(RecenziaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RecenziaTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TrailerLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TrailerTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(DlzkaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DlzkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 34, Short.MAX_VALUE)
                            .addComponent(ObsahLabel)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NazovLabel)
                    .addComponent(NazovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HodnotenieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HodnotenieLabel))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(reziserTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pridajReziseraButton1)
                            .addComponent(zmazReziseraButton2)
                            .addComponent(jLabel8)
                            .addComponent(reziserWikiTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(scenaristaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pridajScenaristuButton1)
                            .addComponent(zmazScenaristuButton2)
                            .addComponent(jLabel9)
                            .addComponent(scenaristaZivotopisTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HerciLabel)
                            .addComponent(menoHercaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(hercovZivotopiTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pridajHercaButton1)
                            .addComponent(zmazHercaButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zanerTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pridajButton2)
                            .addComponent(zmazZanerButton)
                            .addComponent(ZanerLabel))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatLabel)
                            .addComponent(pridajStatTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pridajStatButton2)
                            .addComponent(zmazStatButton4)
                            .addComponent(PremieraLabel)
                            .addComponent(rokTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesiac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(den, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DlzkaLabel)
                                .addComponent(DlzkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ObsahLabel))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TrailerLabel)
                            .addComponent(TrailerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RecenziaLabel)
                            .addComponent(RecenziaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CancelButton)
                            .addComponent(OKButton))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-mm-dd");
        FilmDao sqlfilm = FilmDaoFactory.INSTANCE.getFilmDao();
        Film film = new Film();
        id=sqlfilm.idecko();
        film.setId(id);
        
        int hodnotenie;
        String kont2 = HodnotenieTextField.getText();
        if (kont2.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste hodnotenie!");
            return;
        } else {
            hodnotenie = Integer.parseInt(HodnotenieTextField.getText());
        }        
        film.setHodnotenie(hodnotenie);
        
        String nazov = NazovTextField.getText();
        if (nazov.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste nazov!");
            return;
        }        
        film.setNazov(nazov);
        
        
        int dlzka;
        String kont3 = DlzkaTextField.getText();
        if (kont3.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste dlzku filmu!");
            return;
        } else {
            dlzka = Integer.parseInt(DlzkaTextField.getText());
        }        
        film.setDlzka(dlzka);
        
        
        Date datum = null;
        try {
            datum = sdf.parse(rokTextField.getText()+"-"+mesiac.getText()+"-"+den.getText());
        } catch (ParseException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (datum == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste premieru!");
            return;
        }        
        film.setPremiera(datum);
        
        String obsah = ObsahTextArea.getText();
        if (obsah.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste obsah!");
            return;
        }        
        
        film.setObsah(obsah);
        URL trailer = null;
        try {
            trailer = new URL(TrailerTextField.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (trailer == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste trailer!");
            return;
        }        
        film.setTrailer(trailer);        
        
        URL recenzia = null;
        try {
            recenzia = new URL(RecenziaTextField.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (recenzia == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste recenziu!");
            return;
        }        
        film.setRecenzia(recenzia);
        
        
        sqlfilm.pridat(film);
        StatDao sqlstat = StatDaoFactory.INSTANCE.getStatDao();
        HerecDao sqlherec = HerecDaoFactory.INSTANCE.getHerecDao();
        ZanerDao sqlzaner = ZanerDaoFactory.INSTANCE.getZanerDao();
        ScenaristaDao sqlscenarista = ScenaristaDaoFactory.INSTANCE.getScenaristaDao();
        ReziserDao sqlreziser = ReziserDaoFactory.INSTANCE.getReziserDao();
        System.out.println(reziseri.toString());
        for (Herec herec : herci) {
            sqlherec.pridat(herec);
        }
        for (Stat stat : staty) {
            sqlstat.pridat(stat);
        }
        for (Zaner zaner : zanre) {
            sqlzaner.pridat(zaner);
        }
        for(Scenarista scenarista:scenaristi){
        sqlscenarista.pridat(scenarista);}
       
        for(Reziser reziser : reziseri){
        sqlreziser.pridat(reziser);}
        JOptionPane.showMessageDialog(null,"Film bol uspesne pridany");
         this.setVisible(false);
    }//GEN-LAST:event_OKButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.setVisible(false);
       this.disable();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void rokTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rokTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rokTextFieldActionPerformed

    private void menoHercaTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoHercaTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menoHercaTextField1ActionPerformed

    private void TrailerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrailerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrailerTextFieldActionPerformed

    private void pridajButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajButton2ActionPerformed
        Zaner zaner = new Zaner();
       
        String menoZanra = zanerTextField1.getText();
        if (menoZanra.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zaner!");
            return;
        } 
        zaner.setId(id);
        zaner.setMeno(menoZanra);
        zanre.add(zaner);
        refreshZanre();
        zanerTextField1.setText("");
    }//GEN-LAST:event_pridajButton2ActionPerformed

    private void pridajStatButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajStatButton2ActionPerformed
      Stat stat = new Stat();
      
      String menoStatu =pridajStatTextField1.getText();
        if (menoStatu.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste stat!");
            return;
        } 
        
        stat.setId(id);
        stat.setNazov(menoStatu);
        staty.add(stat);
        refreshStaty();
        pridajStatTextField1.setText("");
    }//GEN-LAST:event_pridajStatButton2ActionPerformed

    private void zmazZanerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmazZanerButtonActionPerformed
        Zaner zaner = (Zaner) zoznamZanreList.getSelectedValue();
        zanre.remove(zaner);
        refreshZanre();
        
        
    }//GEN-LAST:event_zmazZanerButtonActionPerformed

    private void zmazHercaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmazHercaButtonActionPerformed
        Herec herec = (Herec) zoznamHercovList1.getSelectedValue();
        herci.remove(herec);
        refreshHerci();
    }//GEN-LAST:event_zmazHercaButtonActionPerformed

    private void HodnotenieTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HodnotenieTextFieldKeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_HodnotenieTextFieldKeyTyped

    private void zmazStatButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmazStatButton4ActionPerformed
        Stat stat = (Stat) zoznamStatList.getSelectedValue();
        staty.remove(stat);
        refreshStaty();
        
    }//GEN-LAST:event_zmazStatButton4ActionPerformed

    private void reziserTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reziserTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reziserTextField1ActionPerformed

    private void pridajReziseraButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajReziseraButton1ActionPerformed
       Reziser reziser = new Reziser();

String meno = reziserTextField1.getText();
        if (meno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste meno rezisera!");
            return;
        } 
reziser.setMeno(meno);
URL wiki = null;
        try {
            wiki = new URL(reziserWikiTextField1.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (wiki == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zivotopis!");
            return;
        }        
        reziser.setWiki(wiki);
        reziser.setId(id);
        reziseri.add(reziser);
        refreshReziseri();
        reziserTextField1.setText("");
        reziserWikiTextField1.setText("");
        
    }//GEN-LAST:event_pridajReziseraButton1ActionPerformed

    private void pridajScenaristuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajScenaristuButton1ActionPerformed
        Scenarista scenarista = new Scenarista();

String meno = scenaristaTextField1.getText();
        if (meno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste meno scenaristu!");
            return;
        } 
scenarista.setMeno(meno);
URL wiki = null;
        try {
            wiki = new URL(scenaristaZivotopisTextField1.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (wiki == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zivotopis!");
            return;
        }        
        scenarista.setWiki(wiki);
        scenarista.setId(id);
        scenaristi.add(scenarista);
        refreshScenaristi();
    }//GEN-LAST:event_pridajScenaristuButton1ActionPerformed

    private void zmazReziseraButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmazReziseraButton2ActionPerformed
        Reziser reziser = (Reziser) zoznamReziserovList2.getSelectedValue();
        reziseri.remove(reziser);
        refreshReziseri();
    }//GEN-LAST:event_zmazReziseraButton2ActionPerformed

    private void zmazScenaristuButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmazScenaristuButton2ActionPerformed
      Scenarista scenarista = (Scenarista) zoznamScenaristovList3.getSelectedValue();
        scenaristi.remove(scenarista);
        refreshScenaristi();
    }//GEN-LAST:event_zmazScenaristuButton2ActionPerformed

    private void hercovZivotopiTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hercovZivotopiTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hercovZivotopiTextField1ActionPerformed

    private void pridajHercaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajHercaButton1ActionPerformed
        Herec herec = new Herec();
        herec.setId(id);
        String meno = menoHercaTextField1.getText();
        if (meno.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste meno herca!");
            return;
        }
        herec.setMeno(meno);
        URL wiki = null;
        try {
            wiki = new URL(hercovZivotopiTextField1.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(PridatFilmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (wiki == null) {
            JOptionPane.showMessageDialog(this, "Nevyplnili ste zivotopis!");
            return;
        }
        herec.setWiki(wiki);

        herci.add(herec);
        refreshHerci();
        hercovZivotopiTextField1.setText("");
        menoHercaTextField1.setText("");
    }//GEN-LAST:event_pridajHercaButton1ActionPerformed
    
    private void refreshHerci(){
       zoznamHercovList1.setListData(this.herci.toArray());
    }
    
    private void refreshScenaristi(){
       zoznamScenaristovList3.setListData(this.scenaristi.toArray());
    }
     private void refreshReziseri(){
      zoznamReziserovList2.setListData(this.reziseri.toArray());
    }
    private void refreshZanre(){
       zoznamZanreList.setListData(this.zanre.toArray());
    }
    private void refreshStaty(){
        zoznamStatList.setListData(this.staty.toArray());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PridatFilmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PridatFilmForm dialog = new PridatFilmForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel DlzkaLabel;
    private javax.swing.JTextField DlzkaTextField;
    private javax.swing.JLabel HerciLabel;
    private javax.swing.JLabel HodnotenieLabel;
    private javax.swing.JTextField HodnotenieTextField;
    private javax.swing.JLabel NazovLabel;
    private javax.swing.JTextField NazovTextField;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel ObsahLabel;
    private javax.swing.JTextArea ObsahTextArea;
    private javax.swing.JLabel PremieraLabel;
    private javax.swing.JLabel RecenziaLabel;
    private javax.swing.JTextField RecenziaTextField;
    private javax.swing.JLabel StatLabel;
    private javax.swing.JLabel TrailerLabel;
    private javax.swing.JTextField TrailerTextField;
    private javax.swing.JLabel ZanerLabel;
    private javax.swing.JTextField den;
    private javax.swing.JTextField hercovZivotopiTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField menoHercaTextField1;
    private javax.swing.JTextField mesiac;
    private javax.swing.JButton pridajButton2;
    private javax.swing.JButton pridajHercaButton1;
    private javax.swing.JButton pridajReziseraButton1;
    private javax.swing.JButton pridajScenaristuButton1;
    private javax.swing.JButton pridajStatButton2;
    private javax.swing.JTextField pridajStatTextField1;
    private javax.swing.JTextField reziserTextField1;
    private javax.swing.JTextField reziserWikiTextField1;
    private javax.swing.JTextField rokTextField;
    private javax.swing.JTextField scenaristaTextField1;
    private javax.swing.JTextField scenaristaZivotopisTextField1;
    private javax.swing.JTextField zanerTextField1;
    private javax.swing.JButton zmazHercaButton;
    private javax.swing.JButton zmazReziseraButton2;
    private javax.swing.JButton zmazScenaristuButton2;
    private javax.swing.JButton zmazStatButton4;
    private javax.swing.JButton zmazZanerButton;
    private javax.swing.JList zoznamHercovList1;
    private javax.swing.JList zoznamReziserovList2;
    private javax.swing.JList zoznamScenaristovList3;
    private javax.swing.JList zoznamStatList;
    private javax.swing.JList zoznamZanreList;
    // End of variables declaration//GEN-END:variables
}
